<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Source Themes Academic 3.2.0">
  <meta name="generator" content="Hugo 0.53" />
  <meta name="author" content="Yamato Kataoka">

  
  
  
  
    
  
  <meta name="description" content="Prediction of Ames Housing Prices Data">

  
  <link rel="alternate" hreflang="en-us" href="../../../project/ames_housing_prices_project/ames-housing-prices/">

  


  

  

  

  

  

  

  
  
  
  <meta name="theme-color" content="#2962ff">
  

  
  
  
  
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.0/css/all.css" integrity="sha384-aOkxzJ5uQz7WBObEZcHvV5JvRW3TUc2rNPA7pe3AwnsUohiw1Vj2Rgx2KSOkF5+h" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.css" integrity="sha256-ygkqlh3CYSUri3LhQxzdcm0n1EQvH2Y+U5S2idbLtxs=" crossorigin="anonymous">

    
    
    
      
    
    
      
      
        
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css" crossorigin="anonymous">
        
      
    

    

    

  

  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700|Roboto:400,400italic,700|Roboto+Mono">
  

  <link rel="stylesheet" href="../../../styles.css">
  

  
  
  

  
  <link rel="alternate" href="../../../index.xml" type="application/rss+xml" title="Yamato Kataoka">
  <link rel="feed" href="../../../index.xml" type="application/rss+xml" title="Yamato Kataoka">
  

  <link rel="manifest" href="../../../site.webmanifest">
  <link rel="icon" type="image/png" href="../../../img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="../../../img/icon-192.png">

  <link rel="canonical" href="../../../project/ames_housing_prices_project/ames-housing-prices/">

  
  
  
  
    
  
  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="og:site_name" content="Yamato Kataoka">
  <meta property="og:url" content="/project/ames_housing_prices_project/ames-housing-prices/">
  <meta property="og:title" content="Ames Housing Prices Project | Yamato Kataoka">
  <meta property="og:description" content="Prediction of Ames Housing Prices Data"><meta property="og:image" content="/project/ames_housing_prices_project/ames-housing-prices/featured.jpg">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2018-12-31T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2018-12-31T00:00:00&#43;00:00">
  

  

  

  <title>Ames Housing Prices Project | Yamato Kataoka</title>

</head>
<body id="top" data-spy="scroll" data-target="#TableOfContents" data-offset="71" >
  <aside class="search-results" id="search">
  <div class="container">
    <section class="search-header">

      <div class="row no-gutters justify-content-between mb-3">
        <div class="col-6">
          <h1>Search</h1>
        </div>
        <div class="col-6 col-search-close">
          <a class="js-search" href="#"><i class="fas fa-times-circle text-muted" aria-hidden="true"></i></a>
        </div>
      </div>

      <div id="search-box">
        
        <input name="q" id="search-query" placeholder="Search..." autocapitalize="off"
        autocomplete="off" autocorrect="off" role="textbox" spellcheck="false" type="search">
        
      </div>

    </section>
    <section class="section-search-results">

      <div id="search-hits">
        
      </div>

    </section>
  </div>
</aside>


<nav class="navbar navbar-light fixed-top navbar-expand-lg py-0" id="navbar-main">
  <div class="container">

    
      <a class="navbar-brand" href="../../../">Yamato Kataoka</a>
      
      <button type="button" class="navbar-toggler" data-toggle="collapse"
              data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span><i class="fas fa-bars"></i></span>
      </button>
      

    
    <div class="collapse navbar-collapse" id="navbar">

      
      
      <ul class="navbar-nav ml-auto">
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="../../../#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="../../../#projects">
            
            <span>Projects</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="../../../#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        

        

        
        
        
          
        

        <li class="nav-item">
          <a class="nav-link" href="../../../files/resume.pdf">
            
            <span>Resume</span>
            
          </a>
        </li>

        
        

      

        

        
        <li class="nav-item">
          <a class="nav-link js-search" href="#"><i class="fas fa-search" aria-hidden="true"></i></a>
        </li>
        

        

        
        <li class="nav-item">
          <a class="nav-link js-dark-toggle" href="#"><i class="fas fa-moon" aria-hidden="true"></i></a>
        </li>
        

      </ul>

    </div>
  </div>
</nav>


<article class="article article-project" itemscope itemtype="http://schema.org/Article">

  













<div class="article-header d-xl-none">
  <div class="featured-image" style="background-image: url('/project/ames_housing_prices_project/ames-housing-prices/featured_hu2301969423d28847f07b78a895726222_35402_800x0_resize_q75_box.jpg');"></div>
  <span class="article-header-caption">Photo by mohamed_hassan on Pixabay</span>
</div>


<div class="container-fluid split-header d-none d-xl-block">
  <div class="row">
    <div class="col-6">
      <div class="split-header-content">
        <h1 itemprop="name">Ames Housing Prices Project</h1>

        

        

<div class="article-metadata">

  
  
  <span itemscope itemprop="author" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Yamato Kataoka">
  </span>
  

  <span class="article-date">
    
    <meta content="2018-12-31 00:00:00 &#43;0000 UTC" itemprop="datePublished">
    <time datetime="2018-12-31 00:00:00 &#43;0000 UTC" itemprop="dateModified">
      Dec 31, 2018
    </time>
  </span>
  <span itemscope itemprop="publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Yamato Kataoka">
  </span>

  

  
  

  
  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    
    <a href="../../../categories/r/">R</a>, 
    
    <a href="../../../categories/survey/">survey</a>, 
    
    <a href="../../../categories/data-analysis/">data analysis</a>
    
  </span>
  
  

  

</div>


        







  










        
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=Ames%20Housing%20Prices%20Project&amp;url=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f&amp;title=Ames%20Housing%20Prices%20Project"
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f&amp;title=Ames%20Housing%20Prices%20Project"
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=Ames%20Housing%20Prices%20Project&amp;body=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


      </div>
    </div>
    <div class="col-6">
      <div class="split-header-image">
        <img src="../../../project/ames_housing_prices_project/ames-housing-prices/featured_hu2301969423d28847f07b78a895726222_35402_680x500_fill_q90_box_smart1.jpg" itemprop="image" alt="">
        <span class="article-header-caption">Photo by mohamed_hassan on Pixabay</span>
      </div>
    </div>
  </div>
</div>

<div class="article-container d-xl-none">
  <h1 itemprop="name">Ames Housing Prices Project</h1>

  

  

<div class="article-metadata">

  
  
  <span itemscope itemprop="author" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Yamato Kataoka">
  </span>
  

  <span class="article-date">
    
    <meta content="2018-12-31 00:00:00 &#43;0000 UTC" itemprop="datePublished">
    <time datetime="2018-12-31 00:00:00 &#43;0000 UTC" itemprop="dateModified">
      Dec 31, 2018
    </time>
  </span>
  <span itemscope itemprop="publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Yamato Kataoka">
  </span>

  

  
  

  
  
  
  <span class="middot-divider"></span>
  <span class="article-categories">
    <i class="fas fa-folder"></i>
    
    <a href="../../../categories/r/">R</a>, 
    
    <a href="../../../categories/survey/">survey</a>, 
    
    <a href="../../../categories/data-analysis/">data analysis</a>
    
  </span>
  
  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=Ames%20Housing%20Prices%20Project&amp;url=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f"
         target="_blank" rel="noopener">
        <i class="fab fa-facebook-f"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f&amp;title=Ames%20Housing%20Prices%20Project"
         target="_blank" rel="noopener">
        <i class="fab fa-linkedin-in"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f&amp;title=Ames%20Housing%20Prices%20Project"
         target="_blank" rel="noopener">
        <i class="fab fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=Ames%20Housing%20Prices%20Project&amp;body=%2fproject%2fames_housing_prices_project%2fames-housing-prices%2f">
        <i class="fas fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>


  







  









</div>



  <div class="article-container">

    <div class="article-style" itemprop="articleBody">
      


<div id="intro-background" class="section level3">
<h3>Intro &amp; Background</h3>
<p>I’ve just joined the <a href="https://www.kaggle.com/c/house-prices-advanced-regression-techniques">House Prices: Advanced Regression Techniques Competition</a>, whch is a Getting Started competition.</p>
<p>Kaggle describes this competition as follows:</p>
<p>Ask a home buyer to describe their dream house, and they probably won’t begin with the height of the basement ceiling or the proximity to an east-west railroad. But this playground competition’s dataset proves that much more influences price negotiations than the number of bedrooms or a white-picket fence.</p>
<p>With 79 explanatory variables describing (almost) every aspect of residential homes in Ames, Iowa, this competition challenges us to predict the final price of each home.</p>
<p><img src="../../../img/hosue-clipart-sold-1.png" /></p>
<p>SO, we’ll try to answer the question:</p>
<blockquote>
<p>Can you figure out how much a house will sell for?</p>
</blockquote>
</div>
<div id="the-data" class="section level3">
<h3>The Data</h3>
<div id="accessing-data" class="section level4">
<h4>Accessing Data</h4>
<p>Now, we’ll download and get the data directly from the competitions data <a href="https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data">here</a>.</p>
<p>The <a href="http://jse.amstat.org/v19n3/decock.pdf">Ames Housing dataset</a> was compiled by Dean De Cock for use in data science education. It’s an incredible alternative for data scientists looking for a modernized and expanded version of the often cited Boston Housing dataset.</p>
<p>Here’s a brief file description;</p>
<ul>
<li><p>train.csv - the training set</p></li>
<li><p>test.csv - the test set</p></li>
<li><p>data_description.txt - full description of each column, originally prepared by Dean De Cock but lightly edited to match the column names used here</p></li>
<li><p>sample_submission.csv - a benchmark submission from a linear regression on year and month of sale, lot square footage, and number of bedrooms</p></li>
</ul>
<p>You can find the data dictionaries for on <a href="https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data">https://www.kaggle.com/c/house-prices-advanced-regression-techniques/data</a></p>
</div>
<div id="loading-data" class="section level4">
<h4>Loading Data</h4>
<p>We’ll load the data and run the code below to create an object called <code>iowa_data</code>.</p>
<pre class="r"><code># You&#39;d read the data and store data in a tibble
iowa_data &lt;- read_csv(&quot;data/raw_data/train.csv&quot;) </code></pre>
<pre><code>## Parsed with column specification:
## cols(
##   .default = col_character(),
##   Id = col_double(),
##   MSSubClass = col_double(),
##   LotFrontage = col_double(),
##   LotArea = col_double(),
##   OverallQual = col_double(),
##   OverallCond = col_double(),
##   YearBuilt = col_double(),
##   YearRemodAdd = col_double(),
##   MasVnrArea = col_double(),
##   BsmtFinSF1 = col_double(),
##   BsmtFinSF2 = col_double(),
##   BsmtUnfSF = col_double(),
##   TotalBsmtSF = col_double(),
##   `1stFlrSF` = col_double(),
##   `2ndFlrSF` = col_double(),
##   LowQualFinSF = col_double(),
##   GrLivArea = col_double(),
##   BsmtFullBath = col_double(),
##   BsmtHalfBath = col_double(),
##   FullBath = col_double()
##   # ... with 18 more columns
## )</code></pre>
<pre><code>## See spec(...) for full column specifications.</code></pre>
<pre class="r"><code># we&#39;ll make sure Condition1 is a factor &amp; not a char
iowa_data$Condition1 &lt;- as.factor(iowa_data$Condition1)</code></pre>
</div>
</div>
<div id="exploratory-analysis-of-housing-prices-data" class="section level3">
<h3>Exploratory Analysis of Housing Prices Data</h3>
<pre class="r"><code># now we&#39;ll summarize the iowa_data dataframe
summary(iowa_data)</code></pre>
<pre><code>##        Id           MSSubClass      MSZoning          LotFrontage    
##  Min.   :   1.0   Min.   : 20.0   Length:1460        Min.   : 21.00  
##  1st Qu.: 365.8   1st Qu.: 20.0   Class :character   1st Qu.: 59.00  
##  Median : 730.5   Median : 50.0   Mode  :character   Median : 69.00  
##  Mean   : 730.5   Mean   : 56.9                      Mean   : 70.05  
##  3rd Qu.:1095.2   3rd Qu.: 70.0                      3rd Qu.: 80.00  
##  Max.   :1460.0   Max.   :190.0                      Max.   :313.00  
##                                                      NA&#39;s   :259     
##     LotArea          Street             Alley             LotShape        
##  Min.   :  1300   Length:1460        Length:1460        Length:1460       
##  1st Qu.:  7554   Class :character   Class :character   Class :character  
##  Median :  9478   Mode  :character   Mode  :character   Mode  :character  
##  Mean   : 10517                                                           
##  3rd Qu.: 11602                                                           
##  Max.   :215245                                                           
##                                                                           
##  LandContour         Utilities          LotConfig        
##  Length:1460        Length:1460        Length:1460       
##  Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character  
##                                                          
##                                                          
##                                                          
##                                                          
##   LandSlope         Neighborhood         Condition1    Condition2       
##  Length:1460        Length:1460        Norm   :1260   Length:1460       
##  Class :character   Class :character   Feedr  :  81   Class :character  
##  Mode  :character   Mode  :character   Artery :  48   Mode  :character  
##                                        RRAn   :  26                     
##                                        PosN   :  19                     
##                                        RRAe   :  11                     
##                                        (Other):  15                     
##    BldgType          HouseStyle         OverallQual      OverallCond   
##  Length:1460        Length:1460        Min.   : 1.000   Min.   :1.000  
##  Class :character   Class :character   1st Qu.: 5.000   1st Qu.:5.000  
##  Mode  :character   Mode  :character   Median : 6.000   Median :5.000  
##                                        Mean   : 6.099   Mean   :5.575  
##                                        3rd Qu.: 7.000   3rd Qu.:6.000  
##                                        Max.   :10.000   Max.   :9.000  
##                                                                        
##    YearBuilt     YearRemodAdd   RoofStyle           RoofMatl        
##  Min.   :1872   Min.   :1950   Length:1460        Length:1460       
##  1st Qu.:1954   1st Qu.:1967   Class :character   Class :character  
##  Median :1973   Median :1994   Mode  :character   Mode  :character  
##  Mean   :1971   Mean   :1985                                        
##  3rd Qu.:2000   3rd Qu.:2004                                        
##  Max.   :2010   Max.   :2010                                        
##                                                                     
##  Exterior1st        Exterior2nd         MasVnrType          MasVnrArea    
##  Length:1460        Length:1460        Length:1460        Min.   :   0.0  
##  Class :character   Class :character   Class :character   1st Qu.:   0.0  
##  Mode  :character   Mode  :character   Mode  :character   Median :   0.0  
##                                                           Mean   : 103.7  
##                                                           3rd Qu.: 166.0  
##                                                           Max.   :1600.0  
##                                                           NA&#39;s   :8       
##   ExterQual          ExterCond          Foundation       
##  Length:1460        Length:1460        Length:1460       
##  Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character  
##                                                          
##                                                          
##                                                          
##                                                          
##    BsmtQual           BsmtCond         BsmtExposure      
##  Length:1460        Length:1460        Length:1460       
##  Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character  
##                                                          
##                                                          
##                                                          
##                                                          
##  BsmtFinType1         BsmtFinSF1     BsmtFinType2         BsmtFinSF2     
##  Length:1460        Min.   :   0.0   Length:1460        Min.   :   0.00  
##  Class :character   1st Qu.:   0.0   Class :character   1st Qu.:   0.00  
##  Mode  :character   Median : 383.5   Mode  :character   Median :   0.00  
##                     Mean   : 443.6                      Mean   :  46.55  
##                     3rd Qu.: 712.2                      3rd Qu.:   0.00  
##                     Max.   :5644.0                      Max.   :1474.00  
##                                                                          
##    BsmtUnfSF       TotalBsmtSF       Heating           HeatingQC        
##  Min.   :   0.0   Min.   :   0.0   Length:1460        Length:1460       
##  1st Qu.: 223.0   1st Qu.: 795.8   Class :character   Class :character  
##  Median : 477.5   Median : 991.5   Mode  :character   Mode  :character  
##  Mean   : 567.2   Mean   :1057.4                                        
##  3rd Qu.: 808.0   3rd Qu.:1298.2                                        
##  Max.   :2336.0   Max.   :6110.0                                        
##                                                                         
##   CentralAir         Electrical           1stFlrSF       2ndFlrSF   
##  Length:1460        Length:1460        Min.   : 334   Min.   :   0  
##  Class :character   Class :character   1st Qu.: 882   1st Qu.:   0  
##  Mode  :character   Mode  :character   Median :1087   Median :   0  
##                                        Mean   :1163   Mean   : 347  
##                                        3rd Qu.:1391   3rd Qu.: 728  
##                                        Max.   :4692   Max.   :2065  
##                                                                     
##   LowQualFinSF       GrLivArea     BsmtFullBath     BsmtHalfBath    
##  Min.   :  0.000   Min.   : 334   Min.   :0.0000   Min.   :0.00000  
##  1st Qu.:  0.000   1st Qu.:1130   1st Qu.:0.0000   1st Qu.:0.00000  
##  Median :  0.000   Median :1464   Median :0.0000   Median :0.00000  
##  Mean   :  5.845   Mean   :1515   Mean   :0.4253   Mean   :0.05753  
##  3rd Qu.:  0.000   3rd Qu.:1777   3rd Qu.:1.0000   3rd Qu.:0.00000  
##  Max.   :572.000   Max.   :5642   Max.   :3.0000   Max.   :2.00000  
##                                                                     
##     FullBath        HalfBath       BedroomAbvGr    KitchenAbvGr  
##  Min.   :0.000   Min.   :0.0000   Min.   :0.000   Min.   :0.000  
##  1st Qu.:1.000   1st Qu.:0.0000   1st Qu.:2.000   1st Qu.:1.000  
##  Median :2.000   Median :0.0000   Median :3.000   Median :1.000  
##  Mean   :1.565   Mean   :0.3829   Mean   :2.866   Mean   :1.047  
##  3rd Qu.:2.000   3rd Qu.:1.0000   3rd Qu.:3.000   3rd Qu.:1.000  
##  Max.   :3.000   Max.   :2.0000   Max.   :8.000   Max.   :3.000  
##                                                                  
##  KitchenQual         TotRmsAbvGrd     Functional          Fireplaces   
##  Length:1460        Min.   : 2.000   Length:1460        Min.   :0.000  
##  Class :character   1st Qu.: 5.000   Class :character   1st Qu.:0.000  
##  Mode  :character   Median : 6.000   Mode  :character   Median :1.000  
##                     Mean   : 6.518                      Mean   :0.613  
##                     3rd Qu.: 7.000                      3rd Qu.:1.000  
##                     Max.   :14.000                      Max.   :3.000  
##                                                                        
##  FireplaceQu         GarageType         GarageYrBlt   GarageFinish      
##  Length:1460        Length:1460        Min.   :1900   Length:1460       
##  Class :character   Class :character   1st Qu.:1961   Class :character  
##  Mode  :character   Mode  :character   Median :1980   Mode  :character  
##                                        Mean   :1979                     
##                                        3rd Qu.:2002                     
##                                        Max.   :2010                     
##                                        NA&#39;s   :81                       
##    GarageCars      GarageArea      GarageQual         GarageCond       
##  Min.   :0.000   Min.   :   0.0   Length:1460        Length:1460       
##  1st Qu.:1.000   1st Qu.: 334.5   Class :character   Class :character  
##  Median :2.000   Median : 480.0   Mode  :character   Mode  :character  
##  Mean   :1.767   Mean   : 473.0                                        
##  3rd Qu.:2.000   3rd Qu.: 576.0                                        
##  Max.   :4.000   Max.   :1418.0                                        
##                                                                        
##   PavedDrive          WoodDeckSF      OpenPorchSF     EnclosedPorch   
##  Length:1460        Min.   :  0.00   Min.   :  0.00   Min.   :  0.00  
##  Class :character   1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.00  
##  Mode  :character   Median :  0.00   Median : 25.00   Median :  0.00  
##                     Mean   : 94.24   Mean   : 46.66   Mean   : 21.95  
##                     3rd Qu.:168.00   3rd Qu.: 68.00   3rd Qu.:  0.00  
##                     Max.   :857.00   Max.   :547.00   Max.   :552.00  
##                                                                       
##    3SsnPorch       ScreenPorch        PoolArea          PoolQC         
##  Min.   :  0.00   Min.   :  0.00   Min.   :  0.000   Length:1460       
##  1st Qu.:  0.00   1st Qu.:  0.00   1st Qu.:  0.000   Class :character  
##  Median :  0.00   Median :  0.00   Median :  0.000   Mode  :character  
##  Mean   :  3.41   Mean   : 15.06   Mean   :  2.759                     
##  3rd Qu.:  0.00   3rd Qu.:  0.00   3rd Qu.:  0.000                     
##  Max.   :508.00   Max.   :480.00   Max.   :738.000                     
##                                                                        
##     Fence           MiscFeature           MiscVal             MoSold      
##  Length:1460        Length:1460        Min.   :    0.00   Min.   : 1.000  
##  Class :character   Class :character   1st Qu.:    0.00   1st Qu.: 5.000  
##  Mode  :character   Mode  :character   Median :    0.00   Median : 6.000  
##                                        Mean   :   43.49   Mean   : 6.322  
##                                        3rd Qu.:    0.00   3rd Qu.: 8.000  
##                                        Max.   :15500.00   Max.   :12.000  
##                                                                           
##      YrSold       SaleType         SaleCondition        SalePrice     
##  Min.   :2006   Length:1460        Length:1460        Min.   : 34900  
##  1st Qu.:2007   Class :character   Class :character   1st Qu.:129975  
##  Median :2008   Mode  :character   Mode  :character   Median :163000  
##  Mean   :2008                                         Mean   :180921  
##  3rd Qu.:2009                                         3rd Qu.:214000  
##  Max.   :2010                                         Max.   :755000  
## </code></pre>
<p>Each little chunk of output (e.g. “X1”, “Suburb”, “Address”, “Rooms”) tell us about a specific column in our dataframe.</p>
<p>If the column is numeric, though, it will list information about the mean, median, 25th and 75th quartiles, minimum and maximum.</p>
<p>The median year in which the houses in this dataset were built is 1973 (<code>YearBuilt</code>). In addtion, we’ll find that the maximum number or rooms are 14 (<code>TotRmsAbvGrd</code>).</p>
</div>
<div id="prediction-data-analysis" class="section level3">
<h3>Prediction Data Analysis</h3>
<div id="data-splitting" class="section level4">
<h4>Data Splitting</h4>
<p>We’ll take our dataset and split it into a <code>training</code> set and a <code>tuning</code> set.</p>
<pre class="r"><code>## get Index for training set
set.seed(123)
trainIndex &lt;- createDataPartition(iowa_data$Id, p = .7, 
                                  list = FALSE, 
                                  times = 1)

## split into training and tuning set                                  
iowa_train &lt;- iowa_data %&gt;% slice(trainIndex)
iowa_tune &lt;- iowa_data %&gt;% slice(-trainIndex)</code></pre>
</div>
<div id="decision-tree-analysis" class="section level4">
<h4>Decision Tree analysis</h4>
<p>We can then fit a new model using our training data and test it using our testing data.</p>
<p>We’ll be predicting the <code>SalePrice</code> variable. And we start with a narrower set of numeric variables and fit a model that can predict your target variable using the following predictors;</p>
<ul>
<li><p>LotArea</p></li>
<li><p>YearBuilt</p></li>
<li><p>Condition1 (how close to the main road the house is)</p></li>
<li><p>FullBath</p></li>
<li><p>BedroomAbvGr</p></li>
<li><p>TotRmsAbvGrd</p></li>
</ul>
<p>We’re going to use the <code>rpart()</code> function from the <code>rpart package</code> to build our decision tree using the prediction target (<code>SalePrice</code>) and predictors (<code>set of numeric variables</code>).</p>
<pre class="r"><code># build a model to predict housing prices in Iowa using our training set
fit &lt;- rpart(SalePrice ~ TotRmsAbvGrd + FullBath + LotArea + Condition1 +
             YearBuilt + BedroomAbvGr, data = iowa_train)
# get the mean average error for our model
mae(model = fit, data = iowa_tune)</code></pre>
<pre><code>## [1] 37534.09</code></pre>
<p>Then, we just started with one called Mean Absolute Error (also called MAE) for summarizing model quality.</p>
<p>The prediction error for each house is:</p>
<blockquote>
<p><span class="math inline">\(error=actual−predicted\)</span></p>
</blockquote>
<p>With the MAE metric, we take the absolute value of each error. This converts each error to a positive number. We then take the average of those absolute errors. This is our measure of model quality.</p>
<p>We can get the MAE for our model using the <code>mae()</code> function, from the <code>modelr package</code>. The <code>mae()</code> function takes in a model and the dataset to test it against.</p>
<p>On average, our predictions are off by about 37534.09 dollars.</p>
<p>Now, we built prediction model, so we can actually look at the tree it has built.</p>
<pre class="r"><code># plot our regression tree 
plot(fit, uniform=TRUE)
# add text labels &amp; make them 60% as big as they are by default
text(fit, cex=.6)</code></pre>
<p><img src="../../../project/ames_housing_prices_project/index_files/figure-html/model-1.png" width="672" /></p>
<p>We can now use our fitted model to predict the prices of some houses, using the <code>predict()</code> function for our tuning set.</p>
<pre class="r"><code>print(&quot;Making predictions for the following 5 houses:&quot;)
## [1] &quot;Making predictions for the following 5 houses:&quot;
print(head(iowa_tune))
## # A tibble: 6 x 81
##      Id MSSubClass MSZoning LotFrontage LotArea Street Alley LotShape
##   &lt;dbl&gt;      &lt;dbl&gt; &lt;chr&gt;          &lt;dbl&gt;   &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   
## 1     2         20 RL                80    9600 Pave   &lt;NA&gt;  Reg     
## 2     4         70 RL                60    9550 Pave   &lt;NA&gt;  IR1     
## 3     5         60 RL                84   14260 Pave   &lt;NA&gt;  IR1     
## 4     6         50 RL                85   14115 Pave   &lt;NA&gt;  IR1     
## 5     7         20 RL                75   10084 Pave   &lt;NA&gt;  Reg     
## 6    10        190 RL                50    7420 Pave   &lt;NA&gt;  Reg     
## # ... with 73 more variables: LandContour &lt;chr&gt;, Utilities &lt;chr&gt;,
## #   LotConfig &lt;chr&gt;, LandSlope &lt;chr&gt;, Neighborhood &lt;chr&gt;,
## #   Condition1 &lt;fct&gt;, Condition2 &lt;chr&gt;, BldgType &lt;chr&gt;, HouseStyle &lt;chr&gt;,
## #   OverallQual &lt;dbl&gt;, OverallCond &lt;dbl&gt;, YearBuilt &lt;dbl&gt;,
## #   YearRemodAdd &lt;dbl&gt;, RoofStyle &lt;chr&gt;, RoofMatl &lt;chr&gt;,
## #   Exterior1st &lt;chr&gt;, Exterior2nd &lt;chr&gt;, MasVnrType &lt;chr&gt;,
## #   MasVnrArea &lt;dbl&gt;, ExterQual &lt;chr&gt;, ExterCond &lt;chr&gt;, Foundation &lt;chr&gt;,
## #   BsmtQual &lt;chr&gt;, BsmtCond &lt;chr&gt;, BsmtExposure &lt;chr&gt;,
## #   BsmtFinType1 &lt;chr&gt;, BsmtFinSF1 &lt;dbl&gt;, BsmtFinType2 &lt;chr&gt;,
## #   BsmtFinSF2 &lt;dbl&gt;, BsmtUnfSF &lt;dbl&gt;, TotalBsmtSF &lt;dbl&gt;, Heating &lt;chr&gt;,
## #   HeatingQC &lt;chr&gt;, CentralAir &lt;chr&gt;, Electrical &lt;chr&gt;, `1stFlrSF` &lt;dbl&gt;,
## #   `2ndFlrSF` &lt;dbl&gt;, LowQualFinSF &lt;dbl&gt;, GrLivArea &lt;dbl&gt;,
## #   BsmtFullBath &lt;dbl&gt;, BsmtHalfBath &lt;dbl&gt;, FullBath &lt;dbl&gt;,
## #   HalfBath &lt;dbl&gt;, BedroomAbvGr &lt;dbl&gt;, KitchenAbvGr &lt;dbl&gt;,
## #   KitchenQual &lt;chr&gt;, TotRmsAbvGrd &lt;dbl&gt;, Functional &lt;chr&gt;,
## #   Fireplaces &lt;dbl&gt;, FireplaceQu &lt;chr&gt;, GarageType &lt;chr&gt;,
## #   GarageYrBlt &lt;dbl&gt;, GarageFinish &lt;chr&gt;, GarageCars &lt;dbl&gt;,
## #   GarageArea &lt;dbl&gt;, GarageQual &lt;chr&gt;, GarageCond &lt;chr&gt;,
## #   PavedDrive &lt;chr&gt;, WoodDeckSF &lt;dbl&gt;, OpenPorchSF &lt;dbl&gt;,
## #   EnclosedPorch &lt;dbl&gt;, `3SsnPorch` &lt;dbl&gt;, ScreenPorch &lt;dbl&gt;,
## #   PoolArea &lt;dbl&gt;, PoolQC &lt;chr&gt;, Fence &lt;chr&gt;, MiscFeature &lt;chr&gt;,
## #   MiscVal &lt;dbl&gt;, MoSold &lt;dbl&gt;, YrSold &lt;dbl&gt;, SaleType &lt;chr&gt;,
## #   SaleCondition &lt;chr&gt;, SalePrice &lt;dbl&gt;

print(&quot;The predictions are&quot;)
## [1] &quot;The predictions are&quot;
print(predict(fit, head(iowa_tune)))
##        1        2        3        4        5        6 
## 150232.8 150232.8 259061.7 340455.9 200815.1 122309.3

print(&quot;Actual price&quot;)
## [1] &quot;Actual price&quot;
print(head(iowa_tune$SalePrice))
## [1] 181500 140000 250000 143000 307000 118000</code></pre>
<p>So, as you can above, the first house we predicted cost 181,500 dollars and you predicted it would cost 150,232.8 dollars the error is 31,267.2 dollars.</p>
<p>Then now, we are setting the tree depth with the maxdepth argument to control overfitting vs underfitting.</p>
<p>We can use a utility function to help compare MAE scores from different values for maxdepth:</p>
<pre class="r"><code># a function to get the maximum average error for a given max depth. You should pass in
# the target as the name of the target column and the predictors as vector where
# each item in the vector is the name of the column
get_mae &lt;- function(maxdepth, target, predictors, training_data, tuning_data){
    
    # turn the predictors &amp; target into a formula to pass to rpart()
    predictors &lt;- paste(predictors, collapse=&quot;+&quot;)
    formula &lt;- as.formula(paste(target,&quot;~&quot;,predictors,sep = &quot;&quot;))
    
    # build our model
    model &lt;- rpart(formula, data = training_data,
                   control = rpart.control(maxdepth = maxdepth))
    # get the mae
    mae &lt;- mae(model, tuning_data)
    return(mae)
}</code></pre>
<p>We can use a for-loop to compare the accuracy of models built with different values for maxdepth. In this case, the lowest MAE is actually 5.</p>
<pre class="r"><code># target &amp; predictors to feed into our formula
target &lt;- &quot;SalePrice&quot;
predictors &lt;-  c(&quot;TotRmsAbvGrd&quot;, &quot;FullBath&quot;, &quot;LotArea&quot;, &quot;Condition1&quot;, &quot;YearBuilt&quot;, &quot;BedroomAbvGr&quot;)

# get the MAE for maxdepths between 1 &amp; 10
for(i in 1:10){
    mae &lt;- get_mae(maxdepth = i, target = target, predictors = predictors,
                  training_data = iowa_train, tuning_data = iowa_tune)
    print(glue::glue(&quot;Maxdepth: &quot;,i,&quot;\t MAE: &quot;,mae))
}</code></pre>
<pre><code>## Maxdepth: 1   MAE: 46982.6810339195
## Maxdepth: 2   MAE: 41968.2267110074
## Maxdepth: 3   MAE: 39012.1922817192
## Maxdepth: 4   MAE: 38863.924322096
## Maxdepth: 5   MAE: 37534.0937255204
## Maxdepth: 6   MAE: 37534.0937255204
## Maxdepth: 7   MAE: 37534.0937255204
## Maxdepth: 8   MAE: 37534.0937255204
## Maxdepth: 9   MAE: 37534.0937255204
## Maxdepth: 10  MAE: 37534.0937255204</code></pre>
<p>37,534.09 is the lowest mean average error for this dataset, which is given this dataset and our current stopping condition, 6 is the maximum number of nodes.</p>
</div>
<div id="random-forests-analysis" class="section level4">
<h4>Random Forests analysis</h4>
<pre class="r"><code># fit a random forest model to our training set
fitRandomForest &lt;- randomForest(SalePrice ~ TotRmsAbvGrd + FullBath + LotArea + Condition1 +
             YearBuilt + BedroomAbvGr, data = iowa_train)
# get the mean average error for our new model, based on our tuning set
mae(model = fitRandomForest, data = iowa_tune)</code></pre>
<pre><code>## [1] 30894.18</code></pre>
<p>On average, this predictions are off by around 30,894.18 dollars. This is a big improvement over our previous best decision tree.</p>
</div>
</div>
<div id="conclusion" class="section level3">
<h3>Conclusion</h3>
<p>We analyzed and tried to answer the question:</p>
<blockquote>
<p>Can you figure out how much a house will sell for?</p>
</blockquote>
<p>Then, I’ve submitted above prediction values for the <a href="https://www.kaggle.com/c/house-prices-advanced-regression-techniques">House Prices: Advanced Regression Techniques Competition</a>. As a result, I’ve ranked at 3624th.</p>
<p><img src="../../../img/screen-shot.png" /></p>
</div>

    </div>

    


<div class="article-tags">
  
  <a class="badge badge-light" href="../../../tags/r/">R</a>
  
  <a class="badge badge-light" href="../../../tags/dataviz/">dataviz</a>
  
  <a class="badge badge-light" href="../../../tags/analysis/">analysis</a>
  
  <a class="badge badge-light" href="../../../tags/machine-learning/">machine-learning</a>
  
</div>



    






<div class="media author-card" itemscope itemtype="http://schema.org/Person">
  
  <img class="portrait mr-3" src="../../../img/portrait.png" itemprop="image" alt="Avatar">
  
  <div class="media-body">
    <h5 class="card-title" itemprop="name"><a href="../../../">Yamato Kataoka</a></h5>
    
    
    <ul class="network-icon" aria-hidden="true">
      
      
      
      
        
      
      
      
      
      
      <li>
        <a itemprop="sameAs" href="mailto:yamato.kataoka0601@gmail.com" >
          <i class="fas fa-envelope"></i>
        </a>
      </li>
      
      
      
      
        
      
      
      
      
      
        
      
      <li>
        <a itemprop="sameAs" href="//twitter.com/_yamatt" >
          <i class="fab fa-twitter"></i>
        </a>
      </li>
      
      
      
      
        
      
      
      
      
      
        
      
      <li>
        <a itemprop="sameAs" href="//github.com/yamakataoka" >
          <i class="fab fa-github"></i>
        </a>
      </li>
      
    </ul>
  </div>
</div>




    
    

    

      
      
      

      
      
      

      
      
      
    

  </div>
</article>



<div class="container">
  <footer class="site-footer">
  
  <p class="powered-by">
    <a href="../../../privacy/">Privacy Policy</a>
  </p>
  

  <p class="powered-by">
    &copy; 2018 &middot; 

    Powered by the
    <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
    <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

    
    <span class="float-right" aria-hidden="true">
      <a href="#" id="back_to_top">
        <span class="button_icon">
          <i class="fas fa-chevron-up fa-2x"></i>
        </span>
      </a>
    </span>
    
  </p>
</footer>

</div>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cite</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <pre><code class="tex hljs"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-outline-primary my-1 js-copy-cite" href="#" target="_blank">
          <i class="fas fa-copy"></i> Copy
        </a>
        <a class="btn btn-outline-primary my-1 js-download-cite" href="#" target="_blank">
          <i class="fas fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    

    
    
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha256-VsEqElsCHSGmnmHXGQzvoWjWwoznFSZc6hs7ARLRacQ=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.2.5/jquery.fancybox.min.js" integrity="sha256-X5PoE3KU5l+JcX+w09p/wHl9AzK333C4hJ2I9S5mD4M=" crossorigin="anonymous"></script>

      
        
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
        
      

      
      
    

    
    

    
    
    

    
    
    <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script>
      const search_index_filename = "/index.json";
      const i18n = {
        'placeholder': "Search...",
        'results': "results found",
        'no_results': "No results found"
      };
      const content_type = {
        'post': "Posts",
        'project': "Projects",
        'publication' : "Publications",
        'talk' : "Talks"
        };
    </script>
    

    
    

    
    
    <script id="search-hit-fuse-template" type="text/x-template">
      <div class="search-hit" id="summary-{{key}}">
      <div class="search-hit-content">
        <div class="search-hit-name">
          <a href="{{relpermalink}}">{{title}}</a>
          <div class="article-metadata search-hit-type">{{type}}</div>
          <p class="search-hit-description">{{snippet}}</p>
        </div>
      </div>
      </div>
    </script>
    

    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/3.2.1/fuse.min.js" integrity="sha256-VzgmKYmhsGNNN4Ph1kMW+BjoYJM2jV5i4IlFoeZA9XI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/jquery.mark.min.js" integrity="sha256-4HLtjeVgH0eIB3aZ9mLYF6E8oU5chNdjU6p6rrXpl9U=" crossorigin="anonymous"></script>
    

    
    

    
    
    
    
    
    
    
    
    <script src="../../../js/academic.min.d037ee5294b166a79dec317c58aea9cc.js"></script>

    

  </body>
</html>

